In [137]:
import numpy as np


In [138]:
def xmatrix(N):
    matrix = np.eye(N,dtype=int)
    matrix = matrix + np.eye(N,dtype=int)[::-1]
    matrix[1:-1,1:-1]= 1
    
    return matrix

In [139]:
xmatrix(5)

array([[1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [120]:
a = np.arange(0,2**2).reshape(2,2)
a    

array([[0, 1],
       [2, 3]])

In [133]:
def  min_row_col(M):
    a = np.arange(0,M**2).reshape(M,M)
    minRow =[v.sum(axis=0).argmin(),v.sum(axis=1).argmax()]
    return minRow

In [134]:
min_row_col(2)

[0, 2]

In [123]:
v=np.arange(1,10).reshape(3,3)


In [124]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
np.max(v,axis=0)

array([7, 8, 9])

In [127]:
v.min(axis=0)

array([1, 2, 3])

In [128]:
np.argmax(v, axis=0)

array([2, 2, 2], dtype=int64)

In [129]:
v.sum(axis=0).argmax()

2

In [336]:
 # Car speed data:      km/h   RPM
gauges = np.array(     [[  28.2, 2524 ],
                        [  30  , 2677 ],
                        [  31.8, 2830 ],
                        [  33.6, 2983 ],
                        [  35.4, 3136 ]])

s_bias = 1.8
r_bias = 280

gauges



array([[  28.2, 2524. ],
       [  30. , 2677. ],
       [  31.8, 2830. ],
       [  33.6, 2983. ],
       [  35.4, 3136. ]])

In [347]:
def fix_gauge_bias(car_data, speed_bias, rpm_bias):
    array = np.subtract(gauges[:,0:1],s_bias )
    array =np.concatenate([array,car_data[:,1:] - rpm_bias],axis=1)
    return array

In [348]:

adjusted = fix_gauge_bias(gauges, s_bias, r_bias)
adjusted

array([[  26.4, 2244. ],
       [  28.2, 2397. ],
       [  30. , 2550. ],
       [  31.8, 2703. ],
       [  33.6, 2856. ]])

In [349]:
 no_shift = np.array(   [   [  26.4, 2244. ],
                            [  28.2, 2397. ],
                            [  30. , 2550. ],
                            [  31.8, 2703. ],
                            [  33.6, 2856. ]])

In [351]:
yes_shift = no_shift.copy()
yes_shift[0, 1] = yes_shift[0, 0] * 105

In [355]:
yes_shift

array([[  26.4, 2772. ],
       [  28.2, 2397. ],
       [  30. , 2550. ],
       [  31.8, 2703. ],
       [  33.6, 2856. ]])

In [378]:
def was_gear_switched(car_data):
    result = car_data  == no_shift
    final =True
    final = False  if result.all() == True else True
    return final

In [379]:
was_gear_switched(yes_shift)

True

In [447]:
def was_gear_switched(car_data):
    result = car_data  == no_shift
    final = 1
    unique, counts = np.unique(result, return_counts=True)
    final = 1  if result.all() == True else counts[0]+1
    return final

In [448]:
was_gear_switched(yes_shift)

2

In [415]:
result = no_shift == yes_shift
s = result.ravel()
s


    

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [451]:
result = no_shift  == no_shift
s = result.ravel()
num =0
final =1
unique, counts = np.unique(result, return_counts=True)
s =dict(zip(unique, counts))
s 


{True: 10}