In [1]:
import numpy as np


In [2]:
def xmatrix(N):
    matrix = np.eye(N,dtype=int)
    matrix = matrix + np.eye(N,dtype=int)[::-1]
    matrix[1:-1,1:-1]= 1
    
    return matrix

In [3]:
xmatrix(5)

array([[1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [4]:
a = np.arange(0,2**2).reshape(2,2)
a    

array([[0, 1],
       [2, 3]])

In [5]:
def  min_row_col(M):
    a = np.arange(0,M**2).reshape(M,M)
    minRow =[v.sum(axis=0).argmin(),v.sum(axis=1).argmax()]
    return minRow

In [6]:
min_row_col(2)

NameError: name 'v' is not defined

In [7]:
v=np.arange(1,10).reshape(3,3)


In [8]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.max(v,axis=0)

array([7, 8, 9])

In [10]:
v.min(axis=0)

array([1, 2, 3])

In [11]:
np.argmax(v, axis=0)

array([2, 2, 2], dtype=int64)

In [12]:
v.sum(axis=0).argmax()

2

In [13]:
 # Car speed data:      km/h   RPM
gauges = np.array(     [[  28.2, 2524 ],
                        [  30  , 2677 ],
                        [  31.8, 2830 ],
                        [  33.6, 2983 ],
                        [  35.4, 3136 ]])

s_bias = 1.8
r_bias = 280

gauges



array([[  28.2, 2524. ],
       [  30. , 2677. ],
       [  31.8, 2830. ],
       [  33.6, 2983. ],
       [  35.4, 3136. ]])

In [14]:
def fix_gauge_bias(car_data, speed_bias, rpm_bias):
    array = np.subtract(gauges[:,0:1],s_bias )
    array =np.concatenate([array,car_data[:,1:] - rpm_bias],axis=1)
    return array

In [15]:

adjusted = fix_gauge_bias(gauges, s_bias, r_bias)
adjusted

array([[  26.4, 2244. ],
       [  28.2, 2397. ],
       [  30. , 2550. ],
       [  31.8, 2703. ],
       [  33.6, 2856. ]])

In [16]:
 no_shift = np.array(   [   [  26.4, 2244. ],
                            [  28.2, 2397. ],
                            [  30. , 2550. ],
                            [  31.8, 2703. ],
                            [  33.6, 2856. ]])

In [17]:
yes_shift = no_shift.copy()
yes_shift[0, 1] = yes_shift[0, 0] * 105

In [18]:
yes_shift

array([[  26.4, 2772. ],
       [  28.2, 2397. ],
       [  30. , 2550. ],
       [  31.8, 2703. ],
       [  33.6, 2856. ]])

In [19]:
def was_gear_switched(car_data):
    result = car_data  == no_shift
    final =True
    final = False  if result.all() == True else True
    return final

In [20]:
was_gear_switched(yes_shift)

True

In [21]:
def was_gear_switched(car_data):
    result = car_data  == no_shift
    final = 1
    unique, counts = np.unique(result, return_counts=True)
    final = 1  if result.all() == True else counts[0]+1
    return final

In [22]:
was_gear_switched(yes_shift)

2

In [23]:
result = no_shift == yes_shift
s = result.ravel()
s


    

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [87]:
ratio = yes_shift[:,1]/yes_shift[:,0]
ratio

array([105.,  85.,  85.,  85.,  85.])

In [101]:
ratio = no_shift[:,1]/no_shift[:,0]
for x in range(len(ratio)-1):
    result =  abs(ratio[x] - ratio[x+1])/ratio[x]*100>=10
    print(result)



False
False
False
False


In [100]:
result = np.unique(yes_shift[:,1]/yes_shift[:,0])
print(len(result))

2
