In [1]:
import numpy as np


In [5]:
s =np.array([1,2,4,5,6,7])
s

array([1, 2, 4, 5, 6, 7])

In [7]:
floatArray = np.array([1,2,3,4], dtype='float32')
floatArray

array([1., 2., 3., 4.], dtype=float32)

In [8]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [13]:
np.ones((3,5)) # when it is multiple arrays use (())

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3,5),3.5)

array([[3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5]])

In [20]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [22]:
np.random.random((3,5))

array([[0.05009013, 0.23254891, 0.87654717, 0.28626839],
       [0.39526889, 0.91325286, 0.70564291, 0.00737141],
       [0.59468633, 0.96028492, 0.55622151, 0.92244814]])

In [31]:
np.random.randint(0, 12, (3, 3))

array([[ 5,  8,  3],
       [11,  7,  1],
       [ 8,  1,  0]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
x1 =  np.random.random((3,3))
x1

array([[0.28110572, 0.48484125, 0.99657618],
       [0.22181841, 0.64022283, 0.77339847],
       [0.83838599, 0.74377497, 0.09113733]])

In [35]:
x1.ndim

2

In [36]:
x1.shape

(3, 3)

In [37]:
x1.size

9

In [39]:
x2 = np.random.random((3,3,5))
x2

array([[[0.40629867, 0.85007029, 0.68976564, 0.21197154, 0.76732119],
        [0.27660936, 0.42144988, 0.02694187, 0.5793157 , 0.27941765],
        [0.29300829, 0.21407957, 0.31219012, 0.69320154, 0.19859834]],

       [[0.9308873 , 0.43928124, 0.77752075, 0.4311408 , 0.59354769],
        [0.95959909, 0.49966885, 0.84075439, 0.87085998, 0.25408821],
        [0.42089281, 0.70140234, 0.13263424, 0.23379931, 0.04751847]],

       [[0.58892537, 0.96043313, 0.22845224, 0.78760089, 0.10865952],
        [0.76448912, 0.13915032, 0.23902488, 0.66788456, 0.21111519],
        [0.76372226, 0.46453712, 0.2084849 , 0.41500774, 0.69015959]]])

In [43]:
x2[1:2,:,2:3]

array([[[0.77752075],
        [0.84075439],
        [0.13263424]]])

In [46]:
x2[:,:,2:3]

array([[[0.68976564],
        [0.02694187],
        [0.31219012]],

       [[0.77752075],
        [0.84075439],
        [0.13263424]],

       [[0.22845224],
        [0.23902488],
        [0.2084849 ]]])

In [49]:
grid =np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

grid = np.arange(1,27).reshape(3,3,3)

In [58]:
grid = np.arange(1,49).reshape(3,4,4)
grid

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [69]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [70]:
x.reshape(1,3)

array([[1, 2, 3]])

In [71]:
s = np.arange(5,10)
s

array([5, 6, 7, 8, 9])

In [72]:
conc = np.concatenate([x,s])
conc

array([1, 2, 3, 5, 6, 7, 8, 9])

In [73]:
np.add(conc, 10)

array([11, 12, 13, 15, 16, 17, 18, 19])

In [74]:
np.absolute(conc)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [75]:
np.exp(conc)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03])

In [76]:
sum(conc)

41

In [77]:
min(conc)

1

In [78]:
max(conc)

9

In [80]:
conc >2

array([False, False,  True,  True,  True,  True,  True,  True])

In [81]:
conc <8

array([ True,  True,  True,  True,  True,  True, False, False])

In [84]:
np.sum(conc <6)

4

In [85]:
conc

array([1, 2, 3, 5, 6, 7, 8, 9])

In [86]:
[conc[2],conc[5]]

[3, 7]

In [95]:
x =np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
np.sort(x)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])